apiVersion: v1
kind: Service
metadata:
  name: phppgadmin
spec:
  ports:
    - name: phppgadmin
      port: 80
      targetPort: http
  selector:
    app: reporting
    component: phppgadmin
  type: ClusterIP
