apiVersion: v1
kind: Service
metadata:
  name: reporting-db-svc
spec:
  ports:
    - name: postgresql
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    app: reporting
    component: postgres
  type: ClusterIP
